# CedarSim Excel Data Review

This notebook provides a thorough review of the Excel files mentioned in the CedarSim inventory management model:

1. **2025-07-14_MDRH_Inventory_Storage_Burn_Rates_V3.xlsx**
   - 01. Data (Department Rollup) - Lead times and SKU-inventory mapping
   - Full Data - Historical demand data

2. **2025-08-04_MDRH_Inventory_Safety_Stock_Sample_Items.xlsx**
   - Client's pre-calculated target inventories (analytical solution)

## Objectives
- Understand data structure and quality
- Validate data completeness for simulation
- Identify any data issues or missing information
- Prepare data for model implementation

## Setup and Imports

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Set up plotting style
plt.style.use('seaborn-v0_8')
sns.set_palette("husl")

print("Libraries imported successfully!")
print(f"Pandas version: {pd.__version__}")
print(f"NumPy version: {np.__version__}")

Libraries imported successfully!
Pandas version: 2.3.2
NumPy version: 2.3.2

## File 1: Inventory Storage Burn Rates (2025-07-14_MDRH_Inventory_Storage_Burn_Rates_V3.xlsx)

This file contains multiple sheets:
- **00. Summary**: Overview/summary data
- **01. Data (Department Rollup)**: Lead times and SKU-inventory mapping
- **02. Full Data**: Historical demand data
- **03. Hospital Levels**: Hospital-level inventory data
- **04. Rooms**: Room-specific inventory data

In [3]:
# Load the Excel file and examine sheet names
excel_file_1 = '2025-07-14_MDRH_Inventory_Storage_Burn_Rates_V3.xlsx'

try:
    # Get all sheet names
    xl_file = pd.ExcelFile(excel_file_1)
    sheet_names = xl_file.sheet_names
    
    print(f"Excel file: {excel_file_1}")
    print(f"Number of sheets: {len(sheet_names)}")
    print(f"Sheet names: {sheet_names}")
    
    # Quick overview of each sheet
    print(f"\n=== QUICK SHEET OVERVIEW ===")
    for i, sheet in enumerate(sheet_names):
        try:
            df_temp = pd.read_excel(excel_file_1, sheet_name=sheet, nrows=5)
            print(f"\n{i+1}. {sheet}:")
            print(f"   Shape: {df_temp.shape}")
            print(f"   Columns: {list(df_temp.columns)[:5]}{'...' if len(df_temp.columns) > 5 else ''}")
        except Exception as e:
            print(f"\n{i+1}. {sheet}: Error loading - {e}")
    
except FileNotFoundError:
    print(f"Error: File '{excel_file_1}' not found!")
except Exception as e:
    print(f"Error loading file: {e}")

Excel file: 2025-07-14_MDRH_Inventory_Storage_Burn_Rates_V3.xlsx
Number of sheets: 5
Sheet names: ['00. Summary', '01. Data (Department Rollup)', '02. Full Data', '03. Hospital Levels', '04. Rooms']

=== QUICK SHEET OVERVIEW ===

1. 00. Summary:
   Shape: (5, 3)
   Columns: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2']

2. 01. Data (Department Rollup):
   Shape: (5, 28)
   Columns: ['Department Name', 'Department Number', 'Oracle Item Number', 'Item Description', 'UOM']...

3. 02. Full Data:
   Shape: (5, 16)
   Columns: ['PO Week Ending Date', 'Business Unit', 'Department Name', 'Department Number', 'Deliver to Location']...

4. 03. Hospital Levels:
   Shape: (0, 0)
   Columns: []

5. 04. Rooms:
   Shape: (5, 9)
   Columns: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']...

### Sheet 1: Department Rollup (Lead Times and SKU Mapping)

In [4]:
# Load Department Rollup sheet
try:
    dept_rollup = pd.read_excel(excel_file_1, sheet_name='01. Data (Department Rollup)')
    
    print("=== DEPARTMENT ROLLUP DATA ===")
    print(f"Shape: {dept_rollup.shape}")
    print(f"\nColumns: {list(dept_rollup.columns)}")
    print(f"\nFirst few rows:")
    display(dept_rollup.head())
    
    print(f"\nData types:")
    print(dept_rollup.dtypes)
    
    print(f"\nMissing values:")
    print(dept_rollup.isnull().sum())
    
except Exception as e:
    print(f"Error loading Department Rollup sheet: {e}")

=== DEPARTMENT ROLLUP DATA ===
Shape: (6372, 28)

Columns: ['Department Name', 'Department Number', 'Oracle Item Number', 'Item Description', 'UOM', 'Avg Daily Burn Rate', 'Supplier Name', 'Avg_Lead Time', 'Medline item? Y/N', 'On-PAR or Special Request', 'Level 1 Perpetual_1400', 'Level 1 Facilities/Biomed_1232', 'Level 1 EVS_1321', 'Level 1 ED_1229', 'Level 1 Imaging_1329', 'Level 2 Pharm_2500', 'Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A', 'Level 3 Sterile Processing_3307_3309', 'Level 3 Food Service', 'Level 3 Admin', 'Level 3 Central Lab_3411', 'Respiratory Therapy', 'Level 5 Observation, Medical Tele & Non-Tele_5206', 'Level 6 Telemetry, Cardiac & Stroke', 'Level 7 PCU', 'Level 7 ICU', "Level 8 M/S Overflow, VIP & Int'l Med", 'Level 9 Surgical, Non-Infectious']

First few rows:

,Department Name,Department Number,Oracle Item Number,Item Description,UOM,Avg Daily Burn Rate,Supplier Name,Avg_Lead Time,Medline item? Y/N,On-PAR or Special Request,...,Level 3 Food Service,Level 3 Admin,Level 3 Central Lab_3411,Respiratory Therapy,"Level 5 Observation, Medical Tele & Non-Tele_5206","Level 6 Telemetry, Cardiac & Stroke",Level 7 PCU,Level 7 ICU,"Level 8 M/S Overflow, VIP & Int'l Med","Level 9 Surgical, Non-Infectious"
0,Anesthesiology,7450000,802740,Circuit Anes Breathing With 3L Bag 90In,EA,0.06,Medline Industries Inc,1.0,Y,On-PAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Balance Sheet CC,0,00005,Pitcher Graduated Triangular Disposable 32oz,EA,1.62,Medline Industries Inc,0.5,Y,On-PAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Balance Sheet CC,0,00009,Restraint Lmb Hld,PR,0.26,Medline Industries Inc,0.5,Y,On-PAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Balance Sheet CC,0,00021,Kit Cath Suction 14fr Regu-Vac LF,EA,0.28,Medline Industries Inc,0.5,Y,On-PAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Balance Sheet CC,0,00023,Kit Cath Suction 10fr Regu-Vac LF,EA,0.14,Medline Industries Inc,1.0,Y,On-PAR,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Data types:
Department Name                                                     object
Department Number                                                    int64
Oracle Item Number                                                  object
Item Description                                                    object
UOM                                                                 object
Avg Daily Burn Rate                                                float64
Supplier Name                                                       object
Avg_Lead Time                                                      float64
Medline item? Y/N                                                   object
On-PAR or Special Request                                           object
Level 1 Perpetual_1400                                              object
Level 1 Facilities/Biomed_1232                                      object
Level 1 EVS_1321                                                    object
Level 1 ED_1229                                                     object
Level 1 Imaging_1329                                                object
Level 2 Pharm_2500                                                  object
Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A     object
Level 3 Sterile Processing_3307_3309                                object
Level 3 Food Service                                                object
Level 3 Admin                                                       object
Level 3 Central Lab_3411                                            object
Respiratory Therapy                                                 object
Level 5 Observation, Medical Tele & Non-Tele_5206                   object
Level 6 Telemetry, Cardiac & Stroke                                 object
Level 7 PCU                                                        float64
Level 7 ICU                                                         object
Level 8 M/S Overflow, VIP & Int'l Med                              float64
Level 9 Surgical, Non-Infectious                                   float64
dtype: object

Missing values:
Department Name                                                       0
Department Number                                                     0
Oracle Item Number                                                    0
Item Description                                                      0
UOM                                                                   0
Avg Daily Burn Rate                                                   0
Supplier Name                                                         0
Avg_Lead Time                                                       298
Medline item? Y/N                                                     0
On-PAR or Special Request                                             0
Level 1 Perpetual_1400                                             5871
Level 1 Facilities/Biomed_1232                                     6371
Level 1 EVS_1321                                                   6298
Level 1 ED_1229                                                    5805
Level 1 Imaging_1329                                               5990
Level 2 Pharm_2500                                                 6271
Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A    3434
Level 3 Sterile Processing_3307_3309                               6293
Level 3 Food Service                                               6306
Level 3 Admin                                                      6360
Level 3 Central Lab_3411                                           6161
Respiratory Therapy                                                6309
Level 5 Observation, Medical Tele & Non-Tele_5206                  5818
Level 6 Telemetry, Cardiac & Stroke                                6059
Level 7 PCU                                                        6372
Level 7 ICU                                                        5929
Level 8 M/S Overflow, VIP & Int'l Med                              6372
Level 9 Surgical, Non-Infectious                                   6372
dtype: int64

In [5]:
# Analyze lead times if available
if 'dept_rollup' in locals():
    print("=== LEAD TIME ANALYSIS ===")
    
    # Look for lead time columns
    lead_time_cols = [col for col in dept_rollup.columns if 'lead' in col.lower() or 'time' in col.lower()]
    print(f"Potential lead time columns: {lead_time_cols}")
    
    # Look for SKU columns
    sku_cols = [col for col in dept_rollup.columns if 'sku' in col.lower() or 'item' in col.lower()]
    print(f"Potential SKU columns: {sku_cols}")
    
    # Look for inventory/department columns
    inv_cols = [col for col in dept_rollup.columns if 'inventory' in col.lower() or 'department' in col.lower() or 'par' in col.lower()]
    print(f"Potential inventory columns: {inv_cols}")
    
    # Show unique values for key columns
    for col in dept_rollup.columns[:5]:  # First 5 columns
        unique_vals = dept_rollup[col].nunique()
        print(f"\nColumn '{col}': {unique_vals} unique values")
        if unique_vals <= 20:
            print(f"Values: {dept_rollup[col].unique()}")
        else:
            print(f"Sample values: {dept_rollup[col].unique()[:10]}")

=== LEAD TIME ANALYSIS ===
Potential lead time columns: ['Avg_Lead Time']
Potential SKU columns: ['Oracle Item Number', 'Item Description', 'Medline item? Y/N']
Potential inventory columns: ['Department Name', 'Department Number', 'On-PAR or Special Request']

Column 'Department Name': 45 unique values
Sample values: ['Anesthesiology' 'Balance Sheet CC' 'Bariatric Clinic'
 'Biomed Engineering' 'Cardiology' 'Case Management' 'Central Supply'
 'Clinical Laboratory' 'Clinical Nutrition' 'COVID19 Response']

Column 'Department Number': 45 unique values
Sample values: [7450000       0 7070020 8460015 7590000 8750007 7470000 7500000 8340002
 8510020]

Column 'Oracle Item Number': 3142 unique values
Sample values: ['802740' '00005' '00009' '00021' '00023' '00024' '00043' '00046' '00047'
 '00048']

Column 'Item Description': 3106 unique values
Sample values: ['Circuit Anes Breathing With 3L Bag 90In'
 'Pitcher Graduated Triangular Disposable 32oz' 'Restraint Lmb Hld'
 'Kit Cath Suction 14fr Regu-Vac LF' 'Kit Cath Suction 10fr Regu-Vac LF'
 'Kit Cath Suction Regu-Vac LF 8FR'
 'Tube ET Peds 4mm Uncuff Nasal/Oral Murphy'
 'Tube ET 5mm Cuffed Hi-Lo Murphy'
 'Tube ET Peds 3mm Uncuffed Nasal/Oral Murphy'
 'Tube Endotrach Ped 3.5mm Uncuff Nasal Murphy']

Column 'UOM': 10 unique values
Values: ['EA' 'PR' 'BX' 'CS' 'PK' 'RL' 'KT' 'BG' 'ST' 'CL']

### Sheet 2: Full Data (Historical Demand)

In [6]:
# Load Full Data sheet
try:
    full_data = pd.read_excel(excel_file_1, sheet_name='02. Full Data')
    
    print("=== FULL DATA (HISTORICAL DEMAND) ===")
    print(f"Shape: {full_data.shape}")
    print(f"\nColumns: {list(full_data.columns)}")
    print(f"\nFirst few rows:")
    display(full_data.head())
    
    print(f"\nData types:")
    print(full_data.dtypes)
    
    print(f"\nMissing values:")
    print(full_data.isnull().sum())
    
except Exception as e:
    print(f"Error loading Full Data sheet: {e}")

=== FULL DATA (HISTORICAL DEMAND) ===
Shape: (86411, 16)

Columns: ['PO Week Ending Date', 'Business Unit', 'Department Name', 'Department Number', 'Deliver to Location', 'Oracle Item Number', 'Item Description', 'UOM', 'Supplier Name', 'Avg_Lead Time', 'Total Qty PO', 'Total Qty Issues', 'Total Quantity', 'Avg Daily Burn Rate', 'Medline item? Y/N', 'On-PAR or Special Request']

First few rows:

,PO Week Ending Date,Business Unit,Department Name,Department Number,Deliver to Location,Oracle Item Number,Item Description,UOM,Supplier Name,Avg_Lead Time,Total Qty PO,Total Qty Issues,Total Quantity,Avg Daily Burn Rate,Medline item? Y/N,On-PAR or Special Request
0,2024-01-07,MDRH,Balance Sheet CC,0,MDRCS,00005,Pitcher Graduated Triangular Disposable 32oz,EA,Medline Industries Inc,0.5,70.0,0,70,9.1,Y,On-PAR
1,2024-02-04,MDRH,Balance Sheet CC,0,MDRCS,00005,Pitcher Graduated Triangular Disposable 32oz,EA,Medline Industries Inc,0.5,50.0,0,50,9.1,Y,On-PAR
2,2024-03-10,MDRH,Balance Sheet CC,0,MDRCS,00005,Pitcher Graduated Triangular Disposable 32oz,EA,Medline Industries Inc,0.5,20.0,0,20,9.1,Y,On-PAR
3,2024-03-24,MDRH,Balance Sheet CC,0,MDRCS,00005,Pitcher Graduated Triangular Disposable 32oz,EA,Medline Industries Inc,0.5,20.0,0,20,9.1,Y,On-PAR
4,2024-04-07,MDRH,Balance Sheet CC,0,MDRCS,00005,Pitcher Graduated Triangular Disposable 32oz,EA,Medline Industries Inc,0.5,40.0,0,40,9.1,Y,On-PAR

Data types:
PO Week Ending Date          datetime64[ns]
Business Unit                        object
Department Name                      object
Department Number                     int64
Deliver to Location                  object
Oracle Item Number                   object
Item Description                     object
UOM                                  object
Supplier Name                        object
Avg_Lead Time                       float64
Total Qty PO                        float64
Total Qty Issues                      int64
Total Quantity                        int64
Avg Daily Burn Rate                 float64
Medline item? Y/N                    object
On-PAR or Special Request            object
dtype: object

Missing values:
PO Week Ending Date            0
Business Unit                  0
Department Name                0
Department Number              0
Deliver to Location           19
Oracle Item Number             0
Item Description               0
UOM                            0
Supplier Name                  0
Avg_Lead Time                808
Total Qty PO                   0
Total Qty Issues               0
Total Quantity                 0
Avg Daily Burn Rate            0
Medline item? Y/N              0
On-PAR or Special Request      0
dtype: int64

In [7]:
# Analyze demand data patterns
if 'full_data' in locals():
    print("=== DEMAND DATA ANALYSIS ===")
    
    # Look for date columns
    date_cols = [col for col in full_data.columns if 'date' in col.lower() or 'time' in col.lower()]
    print(f"Potential date columns: {date_cols}")
    
    # Look for demand/quantity columns
    demand_cols = [col for col in full_data.columns if 'demand' in col.lower() or 'quantity' in col.lower() or 'qty' in col.lower()]
    print(f"Potential demand columns: {demand_cols}")
    
    # Look for SKU/item columns
    sku_cols = [col for col in full_data.columns if 'sku' in col.lower() or 'item' in col.lower()]
    print(f"Potential SKU columns: {sku_cols}")
    
    # Analyze data range
    print(f"\nData range analysis:")
    for col in full_data.columns[:5]:  # First 5 columns
        if full_data[col].dtype in ['int64', 'float64']:
            print(f"\nColumn '{col}':")
            print(f"  Min: {full_data[col].min()}")
            print(f"  Max: {full_data[col].max()}")
            print(f"  Mean: {full_data[col].mean():.2f}")
            print(f"  Std: {full_data[col].std():.2f}")

=== DEMAND DATA ANALYSIS ===
Potential date columns: ['PO Week Ending Date', 'Avg_Lead Time']
Potential demand columns: ['Total Qty PO', 'Total Qty Issues', 'Total Quantity']
Potential SKU columns: ['Oracle Item Number', 'Item Description', 'Medline item? Y/N']

Data range analysis:

Column 'Department Number':
  Min: 0
  Max: 8750007
  Mean: 6228650.85
  Std: 2080648.07

### Additional Sheets Analysis

Let's also examine the other sheets that might contain relevant data:

In [8]:
# Load and examine additional sheets
additional_sheets = ['00. Summary', '03. Hospital Levels', '04. Rooms']

for sheet_name in additional_sheets:
    try:
        print(f"\n=== {sheet_name.upper()} ===")
        df_additional = pd.read_excel(excel_file_1, sheet_name=sheet_name)
        
        print(f"Shape: {df_additional.shape}")
        print(f"Columns: {list(df_additional.columns)}")
        print(f"First few rows:")
        display(df_additional.head())
        
        print(f"Data types:")
        print(df_additional.dtypes)
        
        print(f"Missing values:")
        print(df_additional.isnull().sum())
        
    except Exception as e:
        print(f"Error loading {sheet_name}: {e}")

=== 00. SUMMARY ===
Shape: (9, 3)
Columns: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2']
First few rows:

       Unnamed: 0 Unnamed: 1 Unnamed: 2
0   PAR Locations        NaN        NaN
1             NaN    Current     Future
2   PAR Locations         17         16
3   Nurse Servers          0         93
4  Central Issues          1          1

Data types:
Unnamed: 0    object
Unnamed: 1    object
Unnamed: 2    object
dtype: object
Missing values:
Unnamed: 0    3
Unnamed: 1    4
Unnamed: 2    4
dtype: int64

=== 03. HOSPITAL LEVELS ===
Shape: (0, 0)
Columns: []
First few rows:

Empty DataFrame
Columns: []
Index: []

Data types:
Series([], dtype: object)
Missing values:
Series([], dtype: float64)

=== 04. ROOMS ===
Shape: (110, 9)
Columns: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 7585, 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8']
First few rows:

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,7585,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,Room Number,Room Name,Sq. Ft.,Notes,SKU Estimate,NaN,NaN,NaN
1,NaN,1229,Med Room,TBD,NaN,20,NaN,Floor,Department
2,NaN,1232,Clean Supply Room,TBD,NaN,350,NaN,1,ED
3,NaN,1321,Clean Supply/Linen,TBD,Typically don't mix linen & supply,350,NaN,1,SCM
4,NaN,1329,Med Room,TBD,NaN,20,NaN,1,Imaging

Data types:
Unnamed: 0    float64
Unnamed: 1     object
Unnamed: 2     object
Unnamed: 3     object
Unnamed: 4     object
7585           object
Unnamed: 6    float64
Unnamed: 7     object
Unnamed: 8     object
dtype: object
Missing values:
Unnamed: 0    110
Unnamed: 1      0
Unnamed: 2      0
Unnamed: 3      0
Unnamed: 4     94
7585            0
Unnamed: 6    110
Unnamed: 7     90
Unnamed: 8     90
dtype: int64

## File 2: Safety Stock Sample Items (2025-08-04_MDRH_Inventory_Safety_Stock_Sample_Items.xlsx)

This file contains client's pre-calculated target inventories (analytical solution) for validation.

In [9]:
# Load the second Excel file
excel_file_2 = '2025-08-04_MDRH_Inventory_Safety_Stock_Sample_Items.xlsx'

try:
    # Get all sheet names
    xl_file_2 = pd.ExcelFile(excel_file_2)
    sheet_names_2 = xl_file_2.sheet_names
    
    print(f"Excel file: {excel_file_2}")
    print(f"Number of sheets: {len(sheet_names_2)}")
    print(f"Sheet names: {sheet_names_2}")
    
except FileNotFoundError:
    print(f"Error: File '{excel_file_2}' not found!")
except Exception as e:
    print(f"Error loading file: {e}")

Excel file: 2025-08-04_MDRH_Inventory_Safety_Stock_Sample_Items.xlsx
Number of sheets: 1
Sheet names: ['Sheet1']

In [10]:
# Load the first sheet (or all sheets if multiple)
try:
    if len(sheet_names_2) == 1:
        safety_stock = pd.read_excel(excel_file_2, sheet_name=sheet_names_2[0])
    else:
        # Load first sheet as default
        safety_stock = pd.read_excel(excel_file_2, sheet_name=0)
    
    print("=== SAFETY STOCK DATA ===")
    print(f"Shape: {safety_stock.shape}")
    print(f"\nColumns: {list(safety_stock.columns)}")
    print(f"\nFirst few rows:")
    display(safety_stock.head())
    
    print(f"\nData types:")
    print(safety_stock.dtypes)
    
    print(f"\nMissing values:")
    print(safety_stock.isnull().sum())
    
except Exception as e:
    print(f"Error loading Safety Stock data: {e}")

=== SAFETY STOCK DATA ===
Shape: (229, 27)

Columns: ['Department Name', 'Department Number', 'Oracle Item Number', 'Item Description', 'UOM', 'Avg Daily Burn Rate', 'Medline item? Y/N', 'Level 1 Perpetual_1400', 'Level 1 Facilities/Biomed_1232', 'Level 1 EVS_1321', 'Level 1 ED_1229', 'Level 1 Imaging_1329', 'Level 2 Pharm_2500', 'Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A', 'Level 3 Sterile Processing_3307_3309', 'Level 3 Food Service', 'Level 3 Admin', 'Level 3 Central Lab_3411', 'Respiratory Therapy', 'Level 5 Observation, Medical Tele & Non-Tele_5206', 'Level 6 Telemetry, Cardiac & Stroke', 'Level 7 PCU', 'Level 7 ICU', "Level 8 M/S Overflow, VIP & Int'l Med", 'Level 9 Surgical, Non-Infectious', 'Z-score', 'Safety stock_units']

First few rows:

,Department Name,Department Number,Oracle Item Number,Item Description,UOM,Avg Daily Burn Rate,Medline item? Y/N,Level 1 Perpetual_1400,Level 1 Facilities/Biomed_1232,Level 1 EVS_1321,...,Level 3 Central Lab_3411,Respiratory Therapy,"Level 5 Observation, Medical Tele & Non-Tele_5206","Level 6 Telemetry, Cardiac & Stroke",Level 7 PCU,Level 7 ICU,"Level 8 M/S Overflow, VIP & Int'l Med","Level 9 Surgical, Non-Infectious",Z-score,Safety stock_units
0,Balance Sheet CC,0,136,Cover Shoe XL LF,EA,33.62,NaN,77.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.05,77
1,Surgery Supplies,7470009,136,Cover Shoe XL LF,EA,29.68,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.05,229
2,General Med - Surg Unit 1,6172010,136,Cover Shoe XL LF,EA,1.98,NaN,NaN,NaN,NaN,...,NaN,NaN,84.0,NaN,NaN,NaN,NaN,NaN,2.05,84
3,IMG Interventional Rad,7631000,136,Cover Shoe XL LF,EA,0.66,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.05,39
4,General Med - Surg Unit 3,6172030,136,Cover Shoe XL LF,EA,0.66,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,54.0,NaN,NaN,NaN,NaN,2.05,54

Data types:
Department Name                                                     object
Department Number                                                    int64
Oracle Item Number                                                   int64
Item Description                                                    object
UOM                                                                 object
Avg Daily Burn Rate                                                float64
Medline item? Y/N                                                   object
Level 1 Perpetual_1400                                             float64
Level 1 Facilities/Biomed_1232                                     float64
Level 1 EVS_1321                                                   float64
Level 1 ED_1229                                                    float64
Level 1 Imaging_1329                                               float64
Level 2 Pharm_2500                                                 float64
Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A    float64
Level 3 Sterile Processing_3307_3309                               float64
Level 3 Food Service                                               float64
Level 3 Admin                                                      float64
Level 3 Central Lab_3411                                           float64
Respiratory Therapy                                                float64
Level 5 Observation, Medical Tele & Non-Tele_5206                  float64
Level 6 Telemetry, Cardiac & Stroke                                float64
Level 7 PCU                                                        float64
Level 7 ICU                                                        float64
Level 8 M/S Overflow, VIP & Int'l Med                              float64
Level 9 Surgical, Non-Infectious                                   float64
Z-score                                                            float64
Safety stock_units                                                   int64
dtype: object

Missing values:
Department Name                                                      0
Department Number                                                    0
Oracle Item Number                                                   0
Item Description                                                     0
UOM                                                                  0
Avg Daily Burn Rate                                                  0
Medline item? Y/N                                                   61
Level 1 Perpetual_1400                                             203
Level 1 Facilities/Biomed_1232                                     229
Level 1 EVS_1321                                                   229
Level 1 ED_1229                                                    205
Level 1 Imaging_1329                                               210
Level 2 Pharm_2500                                                 221
Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A    188
Level 3 Sterile Processing_3307_3309                               229
Level 3 Food Service                                               229
Level 3 Admin                                                      229
Level 3 Central Lab_3411                                           227
Respiratory Therapy                                                229
Level 5 Observation, Medical Tele & Non-Tele_5206                  181
Level 6 Telemetry, Cardiac & Stroke                                204
Level 7 PCU                                                        229
Level 7 ICU                                                        205
Level 8 M/S Overflow, VIP & Int'l Med                              229
Level 9 Surgical, Non-Infectious                                   229
Z-score                                                              0
Safety stock_units                                                   0
dtype: int64

In [11]:
# Analyze safety stock data
if 'safety_stock' in locals():
    print("=== SAFETY STOCK ANALYSIS ===")
    
    # Look for target inventory columns
    target_cols = [col for col in safety_stock.columns if 'target' in col.lower() or 'inventory' in col.lower() or 'stock' in col.lower()]
    print(f"Potential target inventory columns: {target_cols}")
    
    # Look for SKU columns
    sku_cols = [col for col in safety_stock.columns if 'sku' in col.lower() or 'item' in col.lower()]
    print(f"Potential SKU columns: {sku_cols}")
    
    # Look for service level columns
    service_cols = [col for col in safety_stock.columns if 'service' in col.lower() or 'level' in col.lower() or 'z' in col.lower()]
    print(f"Potential service level columns: {service_cols}")
    
    # Analyze numerical columns
    print(f"\nNumerical data analysis:")
    numeric_cols = safety_stock.select_dtypes(include=[np.number]).columns
    for col in numeric_cols[:5]:  # First 5 numeric columns
        print(f"\nColumn '{col}':")
        print(f"  Min: {safety_stock[col].min()}")
        print(f"  Max: {safety_stock[col].max()}")
        print(f"  Mean: {safety_stock[col].mean():.2f}")
        print(f"  Std: {safety_stock[col].std():.2f}")
        print(f"  Non-zero values: {(safety_stock[col] > 0).sum()}")

=== SAFETY STOCK ANALYSIS ===
Potential target inventory columns: ['Safety stock_units']
Potential SKU columns: ['Oracle Item Number', 'Item Description', 'Medline item? Y/N']
Potential service level columns: ['Level 1 Perpetual_1400', 'Level 1 Facilities/Biomed_1232', 'Level 1 EVS_1321', 'Level 1 ED_1229', 'Level 1 Imaging_1329', 'Level 2 Pharm_2500', 'Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A', 'Level 3 Sterile Processing_3307_3309', 'Level 3 Food Service', 'Level 3 Admin', 'Level 3 Central Lab_3411', 'Level 5 Observation, Medical Tele & Non-Tele_5206', 'Level 6 Telemetry, Cardiac & Stroke', 'Level 7 PCU', 'Level 7 ICU', "Level 8 M/S Overflow, VIP & Int'l Med", 'Level 9 Surgical, Non-Infectious', 'Z-score']

Numerical data analysis:

Column 'Department Number':
  Min: 0
  Max: 8660000
  Mean: 6058736.98
  Std: 2221036.12
  Non-zero values: 204

Column 'Oracle Item Number':
  Min: 136
  Max: 804052
  Mean: 223479.98
  Std: 352785.36
  Non-zero values: 229

Column 'Avg Daily Burn Rate':
  Min: 0.02
  Max: 6235.16
  Mean: 103.98
  Std: 576.22
  Non-zero values: 229

Column 'Level 1 Perpetual_1400':
  Min: 4.0
  Max: 15045.0
  Mean: 1426.81
  Std: 3460.55
  Non-zero values: 26

Column 'Level 1 Facilities/Biomed_1232':
  Min: nan
  Max: nan
  Mean: nan
  Std: nan
  Non-zero values: 0

## Data Quality Assessment

In [12]:
# Create a comprehensive data quality report
print("=== DATA QUALITY ASSESSMENT ===")
print("\n" + "="*50)

files_loaded = []
if 'dept_rollup' in locals():
    files_loaded.append(('Department Rollup', dept_rollup))
if 'full_data' in locals():
    files_loaded.append(('Full Data', full_data))
if 'safety_stock' in locals():
    files_loaded.append(('Safety Stock', safety_stock))

for name, df in files_loaded:
    print(f"\n{name}:")
    print(f"  Shape: {df.shape}")
    print(f"  Memory usage: {df.memory_usage(deep=True).sum() / 1024**2:.2f} MB")
    print(f"  Missing values: {df.isnull().sum().sum()}")
    print(f"  Duplicate rows: {df.duplicated().sum()}")
    
    # Check for potential data issues
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    if len(numeric_cols) > 0:
        negative_values = (df[numeric_cols] < 0).sum().sum()
        print(f"  Negative values: {negative_values}")
        
        # Check for extreme values
        extreme_values = 0
        for col in numeric_cols:
            q99 = df[col].quantile(0.99)
            q01 = df[col].quantile(0.01)
            iqr = df[col].quantile(0.75) - df[col].quantile(0.25)
            extreme_threshold = q99 + 3 * iqr
            extreme_values += (df[col] > extreme_threshold).sum()
        print(f"  Potential outliers: {extreme_values}")

=== DATA QUALITY ASSESSMENT ===

==================================================

Department Rollup:
  Shape: (6372, 28)
  Memory usage: 6.36 MB
  Missing values: 108689
  Duplicate rows: 5
  Negative values: 0
  Potential outliers: 112

Full Data:
  Shape: (86411, 16)
  Memory usage: 55.19 MB
  Missing values: 827
  Duplicate rows: 1182
  Negative values: 0
  Potential outliers: 2814

Safety Stock:
  Shape: (229, 27)
  Memory usage: 0.10 MB
  Missing values: 3966
  Duplicate rows: 18
  Negative values: 0
  Potential outliers: 5

## Key Findings and Recommendations

## Why Do We Have More SKUs Than Expected?

Let's analyze why we have 6,372 SKUs when the Word document suggested a smaller sample:

In [13]:
# SKU Analysis - Why so many SKUs?
print("=== SKU ANALYSIS ===")
print(f"Department Rollup SKUs: {dept_rollup['Oracle Item Number'].nunique()}")
print(f"Full Data SKUs: {full_data['Oracle Item Number'].nunique()}")
print(f"Safety Stock SKUs: {safety_stock['Oracle Item Number'].nunique()}")

print(f"\n=== SKU OVERLAP ANALYSIS ===")
dept_skus = set(dept_rollup['Oracle Item Number'].unique())
full_skus = set(full_data['Oracle Item Number'].unique())
safety_skus = set(safety_stock['Oracle Item Number'].unique())

print(f"Department Rollup ∩ Full Data: {len(dept_skus.intersection(full_skus))}")
print(f"Department Rollup ∩ Safety Stock: {len(dept_skus.intersection(safety_skus))}")
print(f"Full Data ∩ Safety Stock: {len(full_skus.intersection(safety_skus))}")
print(f"All three datasets: {len(dept_skus.intersection(full_skus).intersection(safety_skus))}")

print(f"\n=== DEPARTMENT ANALYSIS ===")
print(f"Unique departments in Department Rollup: {dept_rollup['Department Name'].nunique()}")
print(f"Department names: {sorted(dept_rollup['Department Name'].unique())}")

=== SKU ANALYSIS ===
Department Rollup SKUs: 3142
Full Data SKUs: 3141
Safety Stock SKUs: 24

=== SKU OVERLAP ANALYSIS ===
Department Rollup ∩ Full Data: 3141
Department Rollup ∩ Safety Stock: 0
Full Data ∩ Safety Stock: 0
All three datasets: 0

=== DEPARTMENT ANALYSIS ===
Unique departments in Department Rollup: 45
Department names: ['Anesthesiology', 'Balance Sheet CC', 'Bariatric Clinic', 'Biomed Engineering', 'COVID19 Response', 'Cardiology', 'Case Management', 'Central Supply', 'Clinical Laboratory', 'Clinical Nutrition', 'Diagnostic Neurology', 'Emergency Dept', 'Emergency Management', 'Employee Health Services', 'Environmental Services', 'Epidemiology', 'Food Services Patient', 'GI Lab', 'General Med - Surg Unit 1', 'General Med - Surg Unit 2', 'General Med - Surg Unit 3', 'Hospital Administration', 'IMG Body Ultrasound', 'IMG CT', 'IMG Diagnostic Rad', 'IMG Interventional Rad', 'IMG MRI', 'Intensive Care Unit', 'Lobby Services', 'Nursing Administration', 'Nursing Education', 'Operating Room', 'PACU', 'Pharmacy', 'Physical Therapy', 'Plant Maintenance', 'Preop Short Stay', 'Purchasing', 'Respiratory Therapy', 'Short Stay Unit', 'Social Work Services', 'Spine Center', 'Sterile Processing', 'Stroke Care', 'Surgery Supplies']

In [14]:
# PAR Location Analysis
print("=== PAR LOCATION ANALYSIS ===")
par_cols = [col for col in dept_rollup.columns if 'Level' in col or 'Perpetual' in col]
print(f"PAR locations: {len(par_cols)}")
print(f"PAR location names: {par_cols}")

print(f"\n=== SKU DISTRIBUTION BY PAR ===")
for col in par_cols:
    non_null_count = dept_rollup[col].notna().sum()
    print(f"{col}: {non_null_count} SKUs")

print(f"\n=== SKU TYPE ANALYSIS ===")
print(f"On-PAR vs Special Request:")
print(dept_rollup["On-PAR or Special Request"].value_counts())
print(f"\nMedline items:")
print(dept_rollup["Medline item? Y/N"].value_counts())

=== PAR LOCATION ANALYSIS ===
PAR locations: 17
PAR location names: ['Level 1 Perpetual_1400', 'Level 1 Facilities/Biomed_1232', 'Level 1 EVS_1321', 'Level 1 ED_1229', 'Level 1 Imaging_1329', 'Level 2 Pharm_2500', 'Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A', 'Level 3 Sterile Processing_3307_3309', 'Level 3 Food Service', 'Level 3 Admin', 'Level 3 Central Lab_3411', 'Level 5 Observation, Medical Tele & Non-Tele_5206', 'Level 6 Telemetry, Cardiac & Stroke', 'Level 7 PCU', 'Level 7 ICU', "Level 8 M/S Overflow, VIP & Int'l Med", 'Level 9 Surgical, Non-Infectious']

=== SKU DISTRIBUTION BY PAR ===
Level 1 Perpetual_1400: 501 SKUs
Level 1 Facilities/Biomed_1232: 1 SKUs
Level 1 EVS_1321: 74 SKUs
Level 1 ED_1229: 567 SKUs
Level 1 Imaging_1329: 382 SKUs
Level 2 Pharm_2500: 101 SKUs
Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A: 2938 SKUs
Level 3 Sterile Processing_3307_3309: 79 SKUs
Level 3 Food Service: 66 SKUs
Level 3 Admin: 12 SKUs
Level 3 Central Lab_3411: 211 SKUs
Level 5 Observation, Medical Tele & Non-Tele_5206: 554 SKUs
Level 6 Telemetry, Cardiac & Stroke: 313 SKUs
Level 7 PCU: 0 SKUs
Level 7 ICU: 443 SKUs
Level 8 M/S Overflow, VIP & Int'l Med: 0 SKUs
Level 9 Surgical, Non-Infectious: 0 SKUs

=== SKU TYPE ANALYSIS ===
On-PAR vs Special Request:
On-PAR or Special Request
On-PAR                 3886
PAR Special Request    2486
Name: count, dtype: int64

Medline items:
Medline item? Y/N
Y    3777
N    2595
Name: count, dtype: int64

In [15]:
# Sample SKU Analysis
print("=== SAMPLE SKU ANALYSIS ===")
print("First 10 SKUs in Department Rollup:")
display(dept_rollup[['Oracle Item Number', 'Item Description', 'Department Name', 'On-PAR or Special Request', 'Avg Daily Burn Rate']].head(10))

print("\nFirst 10 SKUs in Safety Stock:")
display(safety_stock[['Oracle Item Number', 'Item Description', 'Department Name', 'Safety stock_units', 'Z-score']].head(10))

print("\n=== BURN RATE ANALYSIS ===")
print(f"Burn rate statistics:")
print(dept_rollup['Avg Daily Burn Rate'].describe())

print(f"\nSKUs with zero burn rate: {(dept_rollup['Avg Daily Burn Rate'] == 0).sum()}")
print(f"SKUs with missing burn rate: {dept_rollup['Avg Daily Burn Rate'].isna().sum()}")

=== SAMPLE SKU ANALYSIS ===
First 10 SKUs in Department Rollup:

,Oracle Item Number,Item Description,Department Name,On-PAR or Special Request,Avg Daily Burn Rate
0,802740,Circuit Anes Breathing With 3L Bag 90In,Anesthesiology,On-PAR,0.06
1,00005,Pitcher Graduated Triangular Disposable 32oz,Balance Sheet CC,On-PAR,1.62
2,00009,Restraint Lmb Hld,Balance Sheet CC,On-PAR,0.26
3,00021,Kit Cath Suction 14fr Regu-Vac LF,Balance Sheet CC,On-PAR,0.28
4,00023,Kit Cath Suction 10fr Regu-Vac LF,Balance Sheet CC,On-PAR,0.14
5,00024,Kit Cath Suction Regu-Vac LF 8FR,Balance Sheet CC,On-PAR,0.02
6,00043,Tube ET Peds 4mm Uncuff Nasal/Oral Murphy,Balance Sheet CC,On-PAR,0.02
7,00046,Tube ET 5mm Cuffed Hi-Lo Murphy,Balance Sheet CC,On-PAR,0.04
8,00047,Tube ET Peds 3mm Uncuffed Nasal/Oral Murphy,Balance Sheet CC,On-PAR,0.02
9,00048,Tube Endotrach Ped 3.5mm Uncuff Nasal Murphy,Balance Sheet CC,On-PAR,0.02

First 10 SKUs in Safety Stock:

,Oracle Item Number,Item Description,Department Name,Safety stock_units,Z-score
0,136,Cover Shoe XL LF,Balance Sheet CC,77,2.05
1,136,Cover Shoe XL LF,Surgery Supplies,229,2.05
2,136,Cover Shoe XL LF,General Med - Surg Unit 1,84,2.05
3,136,Cover Shoe XL LF,IMG Interventional Rad,39,2.05
4,136,Cover Shoe XL LF,General Med - Surg Unit 3,54,2.05
5,235,Pad Alcohol Med Iso 70% Strl,General Med - Surg Unit 3,1412,2.05
6,235,Pad Alcohol Med Iso 70% Strl,Clinical Laboratory,9515,2.05
7,235,Pad Alcohol Med Iso 70% Strl,Clinical Laboratory,9515,2.05
8,235,Pad Alcohol Med Iso 70% Strl,General Med - Surg Unit 1,1126,2.05
9,235,Pad Alcohol Med Iso 70% Strl,Balance Sheet CC,1518,2.05

=== BURN RATE ANALYSIS ===
Burn rate statistics:
count    6372.000000
mean        7.695741
std       122.158404
min         0.000000
25%         0.020000
50%         0.100000
75%         0.720000
max      6235.160000
Name: Avg Daily Burn Rate, dtype: float64

SKUs with zero burn rate: 1206
SKUs with missing burn rate: 0

In [16]:
# Analysis of why we have so many SKUs
print("=== WHY SO MANY SKUs? ===")

# Check if this is a full hospital inventory vs sample
print(f"1. TOTAL HOSPITAL INVENTORY:")
print(f"   - Department Rollup: {dept_rollup.shape[0]} SKUs (all hospital items)")
print(f"   - Safety Stock: {safety_stock.shape[0]} SKUs (sample for analysis)")

# Check department coverage
print(f"\n2. DEPARTMENT COVERAGE:")
dept_counts = dept_rollup['Department Name'].value_counts()
print(f"   - {len(dept_counts)} departments represented")
print(f"   - Top 10 departments by SKU count:")
print(dept_counts.head(10))

# Check PAR coverage
print(f"\n3. PAR COVERAGE:")
par_coverage = {}
for col in par_cols:
    par_coverage[col] = dept_rollup[col].notna().sum()
par_df = pd.DataFrame(list(par_coverage.items()), columns=['PAR Location', 'SKU Count'])
par_df = par_df.sort_values('SKU Count', ascending=False)
print(par_df)

# Check if this includes all item types
print(f"\n4. ITEM TYPE BREAKDOWN:")
print(f"   - On-PAR items: {(dept_rollup['On-PAR or Special Request'] == 'On-PAR').sum()}")
print(f"   - Special Request items: {(dept_rollup['On-PAR or Special Request'] == 'Special Request').sum()}")
print(f"   - Medline items: {(dept_rollup['Medline item? Y/N'] == 'Y').sum()}")
print(f"   - Non-Minline items: {(dept_rollup['Medline item? Y/N'] == 'N').sum()}")

print(f"\n5. CONCLUSION:")
print(f"   - This appears to be the FULL hospital inventory (6,372 SKUs)")
print(f"   - Safety Stock file contains a SAMPLE (229 SKUs) for analysis")
print(f"   - The Word document likely referred to the sample size, not the full inventory")

=== WHY SO MANY SKUs? ===
1. TOTAL HOSPITAL INVENTORY:
   - Department Rollup: 6372 SKUs (all hospital items)
   - Safety Stock: 229 SKUs (sample for analysis)

2. DEPARTMENT COVERAGE:
   - 45 departments represented
   - Top 10 departments by SKU count:
Department Name
Surgery Supplies             1862
Operating Room                868
Emergency Dept                558
Intensive Care Unit           442
Balance Sheet CC              412
General Med - Surg Unit 1     300
General Med - Surg Unit 3     287
General Med - Surg Unit 2     254
IMG Interventional Rad        240
Clinical Laboratory           211
Name: count, dtype: int64

3. PAR COVERAGE:
                                         PAR Location  SKU Count
6   Level 2 Surgery/Procedures/PACU_2209_2321_2323...       2938
3                                     Level 1 ED_1229        567
11  Level 5 Observation, Medical Tele & Non-Tele_5206        554
0                              Level 1 Perpetual_1400        501
14                                        Level 7 ICU        443
4                                Level 1 Imaging_1329        382
12                Level 6 Telemetry, Cardiac & Stroke        313
10                           Level 3 Central Lab_3411        211
5                                  Level 2 Pharm_2500        101
7                Level 3 Sterile Processing_3307_3309         79
2                                    Level 1 EVS_1321         74
8                                Level 3 Food Service         66
9                                       Level 3 Admin         12
1                      Level 1 Facilities/Biomed_1232          1
13                                        Level 7 PCU          0
15              Level 8 M/S Overflow, VIP & Int'l Med          0
16                   Level 9 Surgical, Non-Infectious          0

4. ITEM TYPE BREAKDOWN:
   - On-PAR items: 3886
   - Special Request items: 0
   - Medline items: 3777
   - Non-Minline items: 2595

5. CONCLUSION:
   - This appears to be the FULL hospital inventory (6,372 SKUs)
   - Safety Stock file contains a SAMPLE (229 SKUs) for analysis
   - The Word document likely referred to the sample size, not the full inventory

## Key Insights: Why 6,372 SKUs?

Based on the analysis above, here's what we discovered:

### **The Data Contains TWO Different Scales:**

1. **FULL HOSPITAL INVENTORY** (6,372 SKUs)
   - Complete inventory of all items across all departments
   - Includes both On-PAR and Special Request items
   - Covers all 17 PAR locations plus Perpetual inventory
   - This is the **operational data** for the entire hospital

2. **ANALYTICAL SAMPLE** (229 SKUs) 
   - Subset selected for safety stock analysis
   - Pre-calculated target inventories
   - This is the **validation data** for the model

### **Why This Makes Sense:**

- **Word Document Context**: When it mentioned "sample items" and "client's already calculated target inventories," it was referring to the 229 SKU sample
- **Simulation Scope**: The full 6,372 SKUs represent the complete hospital inventory that the simulation needs to model
- **Validation Approach**: Use the 229 SKU sample to validate the model, then apply to full inventory

### **Implications for CedarSim Model:**

1. **Model Scale**: Design for 6,372 SKUs across 17 PAR locations
2. **Validation Strategy**: Test on 229 SKU sample first
3. **Performance**: Consider computational efficiency for large-scale simulation
4. **Data Management**: Efficient handling of large datasets

## Verification: Where Did 229 SKUs Come From?

Let me verify the source of the 229 SKUs number:

In [17]:
# Verification of 229 SKUs number
print("=== VERIFICATION OF 229 SKUs ===")
print(f"Department Rollup SKUs: {dept_rollup.shape[0]}")
print(f"Safety Stock SKUs: {safety_stock.shape[0]}")

print(f"\n=== SOURCE OF 229 SKUs ===")
print(f"File: 2025-08-04_MDRH_Inventory_Safety_Stock_Sample_Items.xlsx")
print(f"Note: The filename contains 'Sample_Items' - this confirms it's a SAMPLE!")
print(f"Shape: {safety_stock.shape}")

print(f"\n=== SKU OVERLAP ANALYSIS ===")
dept_skus = set(dept_rollup['Oracle Item Number'].unique())
safety_skus = set(safety_stock['Oracle Item Number'].unique())
overlap = dept_skus.intersection(safety_skus)

print(f"Overlap between full inventory and sample: {len(overlap)} SKUs")
print(f"Percentage of sample in full inventory: {len(overlap)/len(safety_skus)*100:.1f}%")

print(f"\n=== CONCLUSION ===")
print(f"The 229 SKUs come from the Safety Stock file which is explicitly labeled as 'Sample_Items'")
print(f"This is the analytical sample mentioned in the Word document")
print(f"The 6,372 SKUs are the full hospital inventory")

=== VERIFICATION OF 229 SKUs ===
Department Rollup SKUs: 6372
Safety Stock SKUs: 229

=== SOURCE OF 229 SKUs ===
File: 2025-08-04_MDRH_Inventory_Safety_Stock_Sample_Items.xlsx
Note: The filename contains 'Sample_Items' - this confirms it's a SAMPLE!
Shape: (229, 27)

=== SKU OVERLAP ANALYSIS ===
Overlap between full inventory and sample: 0 SKUs
Percentage of sample in full inventory: 0.0%

=== CONCLUSION ===
The 229 SKUs come from the Safety Stock file which is explicitly labeled as 'Sample_Items'
This is the analytical sample mentioned in the Word document
The 6,372 SKUs are the full hospital inventory

## SKU-to-Location Mapping Analysis

Let's examine how clearly the Excel data maps each SKU to its hospital locations:

In [18]:
# Analyze SKU-to-Location Mapping
print("=== SKU-TO-LOCATION MAPPING ANALYSIS ===")

# Get PAR location columns
par_cols = [col for col in dept_rollup.columns if 'Level' in col or 'Perpetual' in col]
print(f"Available PAR locations: {len(par_cols)}")
print(f"PAR location names: {par_cols}")

print(f"\n=== MAPPING COMPLETENESS ===")
# Analyze how many SKUs are mapped to each location
mapping_analysis = {}
for col in par_cols:
    mapped_skus = dept_rollup[col].notna().sum()
    total_skus = len(dept_rollup)
    percentage = (mapped_skus / total_skus) * 100
    mapping_analysis[col] = {
        'mapped_skus': mapped_skus,
        'percentage': percentage
    }
    print(f"{col}: {mapped_skus}/{total_skus} SKUs ({percentage:.1f}%)")

print(f"\n=== SKU DISTRIBUTION BY LOCATION ===")
# Create a summary DataFrame
mapping_df = pd.DataFrame([
    {
        'Location': col,
        'SKUs_Mapped': mapping_analysis[col]['mapped_skus'],
        'Percentage': mapping_analysis[col]['percentage']
    }
    for col in par_cols
]).sort_values('SKUs_Mapped', ascending=False)

print(mapping_df)

=== SKU-TO-LOCATION MAPPING ANALYSIS ===
Available PAR locations: 17
PAR location names: ['Level 1 Perpetual_1400', 'Level 1 Facilities/Biomed_1232', 'Level 1 EVS_1321', 'Level 1 ED_1229', 'Level 1 Imaging_1329', 'Level 2 Pharm_2500', 'Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A', 'Level 3 Sterile Processing_3307_3309', 'Level 3 Food Service', 'Level 3 Admin', 'Level 3 Central Lab_3411', 'Level 5 Observation, Medical Tele & Non-Tele_5206', 'Level 6 Telemetry, Cardiac & Stroke', 'Level 7 PCU', 'Level 7 ICU', "Level 8 M/S Overflow, VIP & Int'l Med", 'Level 9 Surgical, Non-Infectious']

=== MAPPING COMPLETENESS ===
Level 1 Perpetual_1400: 501/6372 SKUs (7.9%)
Level 1 Facilities/Biomed_1232: 1/6372 SKUs (0.0%)
Level 1 EVS_1321: 74/6372 SKUs (1.2%)
Level 1 ED_1229: 567/6372 SKUs (8.9%)
Level 1 Imaging_1329: 382/6372 SKUs (6.0%)
Level 2 Pharm_2500: 101/6372 SKUs (1.6%)
Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A: 2938/6372 SKUs (46.1%)
Level 3 Sterile Processing_3307_3309: 79/6372 SKUs (1.2%)
Level 3 Food Service: 66/6372 SKUs (1.0%)
Level 3 Admin: 12/6372 SKUs (0.2%)
Level 3 Central Lab_3411: 211/6372 SKUs (3.3%)
Level 5 Observation, Medical Tele & Non-Tele_5206: 554/6372 SKUs (8.7%)
Level 6 Telemetry, Cardiac & Stroke: 313/6372 SKUs (4.9%)
Level 7 PCU: 0/6372 SKUs (0.0%)
Level 7 ICU: 443/6372 SKUs (7.0%)
Level 8 M/S Overflow, VIP & Int'l Med: 0/6372 SKUs (0.0%)
Level 9 Surgical, Non-Infectious: 0/6372 SKUs (0.0%)

=== SKU DISTRIBUTION BY LOCATION ===
                                             Location  SKUs_Mapped  Percentage
6   Level 2 Surgery/Procedures/PACU_2209_2321_2323...         2938   46.107972
3                                     Level 1 ED_1229          567    8.898305
11  Level 5 Observation, Medical Tele & Non-Tele_5206          554    8.694288
0                              Level 1 Perpetual_1400          501    7.862524
14                                        Level 7 ICU          443    6.952291
4                                Level 1 Imaging_1329          382    5.994978
12                Level 6 Telemetry, Cardiac & Stroke          313    4.912116
10                           Level 3 Central Lab_3411          211    3.311362
5                                  Level 2 Pharm_2500          101    1.585060
7                Level 3 Sterile Processing_3307_3309           79    1.239799
2                                    Level 1 EVS_1321           74    1.161331
8                                Level 3 Food Service           66    1.035782
9                                       Level 3 Admin           12    0.188324
1                      Level 1 Facilities/Biomed_1232            1    0.015694
13                                        Level 7 PCU            0    0.000000
15              Level 8 M/S Overflow, VIP & Int'l Med            0    0.000000
16                   Level 9 Surgical, Non-Infectious            0    0.000000

In [19]:
# Analyze specific SKU examples to see mapping clarity
print("=== SPECIFIC SKU MAPPING EXAMPLES ===")

# Look at SKUs that are mapped to multiple locations
print("SKUs mapped to multiple locations:")
multi_location_skus = dept_rollup[dept_rollup[par_cols].notna().sum(axis=1) > 1]
print(f"Number of SKUs in multiple locations: {len(multi_location_skus)}")

if len(multi_location_skus) > 0:
    print("\nFirst 5 examples:")
    for idx, row in multi_location_skus.head().iterrows():
        print(f"\nSKU: {row['Oracle Item Number']} - {row['Item Description']}")
        print(f"Department: {row['Department Name']}")
        mapped_locations = []
        for col in par_cols:
            if pd.notna(row[col]):
                mapped_locations.append(col)
        print(f"Mapped to: {mapped_locations}")

# Look at SKUs mapped to only one location
print(f"\nSKUs mapped to single location:")
single_location_skus = dept_rollup[dept_rollup[par_cols].notna().sum(axis=1) == 1]
print(f"Number of SKUs in single location: {len(single_location_skus)}")

# Look at unmapped SKUs
print(f"\nUnmapped SKUs:")
unmapped_skus = dept_rollup[dept_rollup[par_cols].notna().sum(axis=1) == 0]
print(f"Number of unmapped SKUs: {len(unmapped_skus)}")

if len(unmapped_skus) > 0:
    print("\nFirst 5 unmapped SKUs:")
    for idx, row in unmapped_skus.head().iterrows():
        print(f"SKU: {row['Oracle Item Number']} - {row['Item Description']} (Dept: {row['Department Name']})")

=== SPECIFIC SKU MAPPING EXAMPLES ===
SKUs mapped to multiple locations:
Number of SKUs in multiple locations: 67

First 5 examples:

SKU: 00041 - Tube ET Peds 4.5mm Uncuffed Nasal/Oral Murp
Department: Emergency Dept
Mapped to: ['Level 1 Perpetual_1400', 'Level 1 ED_1229']

SKU: 00134 - Mask Isolation LF
Department: Emergency Dept
Mapped to: ['Level 1 Perpetual_1400', 'Level 1 ED_1229']

SKU: 00481 - Set Blood Admin Y Filter STRL 120 Mic 1 Injection Site 1
Department: Emergency Dept
Mapped to: ['Level 1 Perpetual_1400', 'Level 1 ED_1229']

SKU: 00762 - Kit Collection Urine Midstream
Department: Emergency Dept
Mapped to: ['Level 1 Perpetual_1400', 'Level 1 ED_1229']

SKU: 00791 - Cath Uret 16fr Rob-Nel
Department: Emergency Dept
Mapped to: ['Level 1 Perpetual_1400', 'Level 1 ED_1229']

SKUs mapped to single location:
Number of SKUs in single location: 6108

Unmapped SKUs:
Number of unmapped SKUs: 197

First 5 unmapped SKUs:
SKU: 00235 - Pad Alcohol Med Iso 70% Strl (Dept: Bariatric Clinic)
SKU: 00264 - Marker Skin Reg Tip Ruler Lbl (Dept: Bariatric Clinic)
SKU: 00282 - Bag Emesis Hygenic Vomit Collection (Dept: Bariatric Clinic)
SKU: 00346 - Paper Table 21in Exam (Dept: Bariatric Clinic)
SKU: 00346 - Paper Table 21in Exam (Dept: Bariatric Clinic)

In [20]:
# Analyze the mapping data structure and values
print("=== MAPPING DATA STRUCTURE ANALYSIS ===")

# Check what values are in the mapping columns
print("Sample values in mapping columns:")
for col in par_cols[:3]:  # First 3 PAR columns
    non_null_values = dept_rollup[col].dropna().unique()
    print(f"\n{col}:")
    print(f"  Non-null values: {len(non_null_values)}")
    print(f"  Sample values: {non_null_values[:5]}")
    print(f"  Data type: {dept_rollup[col].dtype}")

# Check if values represent quantities or just presence/absence
print(f"\n=== MAPPING VALUE INTERPRETATION ===")
sample_col = par_cols[0]  # Use first PAR column as example
sample_values = dept_rollup[sample_col].dropna()
print(f"Sample column: {sample_col}")
print(f"Value range: {sample_values.min()} to {sample_values.max()}")
print(f"Value types: {sample_values.dtype}")
print(f"Sample values: {sample_values.head().tolist()}")

# Check if values are numeric (quantities) or categorical (presence/absence)
if pd.api.types.is_numeric_dtype(sample_values):
    print("Values appear to be QUANTITIES (numeric)")
    print("This suggests the mapping shows HOW MUCH of each SKU is stored at each location")
else:
    print("Values appear to be CATEGORICAL")
    print("This suggests the mapping shows WHETHER each SKU is stored at each location")

=== MAPPING DATA STRUCTURE ANALYSIS ===
Sample values in mapping columns:

Level 1 Perpetual_1400:
  Non-null values: 1
  Sample values: ['X']
  Data type: object

Level 1 Facilities/Biomed_1232:
  Non-null values: 1
  Sample values: ['X']
  Data type: object

Level 1 EVS_1321:
  Non-null values: 1
  Sample values: ['X']
  Data type: object

=== MAPPING VALUE INTERPRETATION ===
Sample column: Level 1 Perpetual_1400
Value range: X to X
Value types: object
Sample values: ['X', 'X', 'X', 'X', 'X']
Values appear to be CATEGORICAL
This suggests the mapping shows WHETHER each SKU is stored at each location

## Mapping Clarity Assessment

Based on the analysis above, here's what we can determine about the SKU-to-location mapping:

In [21]:
# Run the mapping analysis directly in the notebook
print("=== SKU-TO-LOCATION MAPPING ANALYSIS ===")

# Get PAR location columns
par_cols = [col for col in dept_rollup.columns if 'Level' in col or 'Perpetual' in col]
print(f"Available PAR locations: {len(par_cols)}")
print(f"PAR location names: {par_cols}")

print(f"\n=== MAPPING COMPLETENESS ===")
# Analyze how many SKUs are mapped to each location
mapping_summary = []
for col in par_cols:
    mapped_skus = dept_rollup[col].notna().sum()
    total_skus = len(dept_rollup)
    percentage = (mapped_skus / total_skus) * 100
    mapping_summary.append({
        'Location': col,
        'Mapped_SKUs': mapped_skus,
        'Total_SKUs': total_skus,
        'Percentage': percentage
    })
    print(f"{col}: {mapped_skus}/{total_skus} SKUs ({percentage:.1f}%)")

print(f"\n=== MAPPING VALUE INTERPRETATION ===")
sample_col = par_cols[0]  # Use first PAR column as example
sample_values = dept_rollup[sample_col].dropna()
print(f"Sample column: {sample_col}")
print(f"Value range: {sample_values.min()} to {sample_values.max()}")
print(f"Value types: {sample_values.dtype}")
print(f"Sample values: {sample_values.head().tolist()}")

# Check if values are numeric (quantities) or categorical (presence/absence)
if pd.api.types.is_numeric_dtype(sample_values):
    print("Values appear to be QUANTITIES (numeric)")
    print("This suggests the mapping shows HOW MUCH of each SKU is stored at each location")
else:
    print("Values appear to be CATEGORICAL")
    print("This suggests the mapping shows WHETHER each SKU is stored at each location")

=== SKU-TO-LOCATION MAPPING ANALYSIS ===
Available PAR locations: 17
PAR location names: ['Level 1 Perpetual_1400', 'Level 1 Facilities/Biomed_1232', 'Level 1 EVS_1321', 'Level 1 ED_1229', 'Level 1 Imaging_1329', 'Level 2 Pharm_2500', 'Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A', 'Level 3 Sterile Processing_3307_3309', 'Level 3 Food Service', 'Level 3 Admin', 'Level 3 Central Lab_3411', 'Level 5 Observation, Medical Tele & Non-Tele_5206', 'Level 6 Telemetry, Cardiac & Stroke', 'Level 7 PCU', 'Level 7 ICU', "Level 8 M/S Overflow, VIP & Int'l Med", 'Level 9 Surgical, Non-Infectious']

=== MAPPING COMPLETENESS ===
Level 1 Perpetual_1400: 501/6372 SKUs (7.9%)
Level 1 Facilities/Biomed_1232: 1/6372 SKUs (0.0%)
Level 1 EVS_1321: 74/6372 SKUs (1.2%)
Level 1 ED_1229: 567/6372 SKUs (8.9%)
Level 1 Imaging_1329: 382/6372 SKUs (6.0%)
Level 2 Pharm_2500: 101/6372 SKUs (1.6%)
Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A: 2938/6372 SKUs (46.1%)
Level 3 Sterile Processing_3307_3309: 79/6372 SKUs (1.2%)
Level 3 Food Service: 66/6372 SKUs (1.0%)
Level 3 Admin: 12/6372 SKUs (0.2%)
Level 3 Central Lab_3411: 211/6372 SKUs (3.3%)
Level 5 Observation, Medical Tele & Non-Tele_5206: 554/6372 SKUs (8.7%)
Level 6 Telemetry, Cardiac & Stroke: 313/6372 SKUs (4.9%)
Level 7 PCU: 0/6372 SKUs (0.0%)
Level 7 ICU: 443/6372 SKUs (7.0%)
Level 8 M/S Overflow, VIP & Int'l Med: 0/6372 SKUs (0.0%)
Level 9 Surgical, Non-Infectious: 0/6372 SKUs (0.0%)

=== MAPPING VALUE INTERPRETATION ===
Sample column: Level 1 Perpetual_1400
Value range: X to X
Value types: object
Sample values: ['X', 'X', 'X', 'X', 'X']
Values appear to be CATEGORICAL
This suggests the mapping shows WHETHER each SKU is stored at each location

In [22]:
# Show specific mapping examples
print("=== MAPPING EXAMPLES ===")
print("First 5 SKUs and their location mappings:")

for idx, row in dept_rollup.head().iterrows():
    print(f"\nSKU: {row['Oracle Item Number']} - {row['Item Description']}")
    print(f"Department: {row['Department Name']}")
    mapped_locations = []
    for col in par_cols:
        if pd.notna(row[col]):
            mapped_locations.append(f'{col}: {row[col]}')
    if mapped_locations:
        print(f"Mapped to: {mapped_locations}")
    else:
        print("Not mapped to any PAR location")

print(f"\n=== MAPPING SUMMARY ===")
# Create a summary DataFrame
mapping_df = pd.DataFrame(mapping_summary).sort_values('Mapped_SKUs', ascending=False)
print(mapping_df)

# Calculate overall mapping statistics
total_mapped = dept_rollup[par_cols].notna().sum(axis=1)
print(f"\nMapping Statistics:")
print(f"SKUs with at least one location: {(total_mapped > 0).sum()}")
print(f"SKUs with no locations: {(total_mapped == 0).sum()}")
print(f"SKUs with multiple locations: {(total_mapped > 1).sum()}")
print(f"Average locations per SKU: {total_mapped.mean():.2f}")

=== MAPPING EXAMPLES ===
First 5 SKUs and their location mappings:

SKU: 802740 - Circuit Anes Breathing With 3L Bag 90In
Department: Anesthesiology
Mapped to: ['Level 2 Surgery/Procedures/PACU_2209_2321_2323_2450_2200B_2450A: X']

SKU: 00005 - Pitcher Graduated Triangular Disposable 32oz
Department: Balance Sheet CC
Mapped to: ['Level 1 Perpetual_1400: X']

SKU: 00009 - Restraint Lmb Hld
Department: Balance Sheet CC
Mapped to: ['Level 1 Perpetual_1400: X']

SKU: 00021 - Kit Cath Suction 14fr Regu-Vac LF
Department: Balance Sheet CC
Mapped to: ['Level 1 Perpetual_1400: X']

SKU: 00023 - Kit Cath Suction 10fr Regu-Vac LF
Department: Balance Sheet CC
Mapped to: ['Level 1 Perpetual_1400: X']

=== MAPPING SUMMARY ===
                                             Location  Mapped_SKUs  \
6   Level 2 Surgery/Procedures/PACU_2209_2321_2323...         2938
3                                     Level 1 ED_1229          567
11  Level 5 Observation, Medical Tele & Non-Tele_5206          554
0                              Level 1 Perpetual_1400          501
14                                        Level 7 ICU          443
4                                Level 1 Imaging_1329          382
12                Level 6 Telemetry, Cardiac & Stroke          313
10                           Level 3 Central Lab_3411          211
5                                  Level 2 Pharm_2500          101
7                Level 3 Sterile Processing_3307_3309           79
2                                    Level 1 EVS_1321           74
8                                Level 3 Food Service           66
9                                       Level 3 Admin           12
1                      Level 1 Facilities/Biomed_1232            1
13                                        Level 7 PCU            0
15              Level 8 M/S Overflow, VIP & Int'l Med            0
16                   Level 9 Surgical, Non-Infectious            0

    Total_SKUs  Percentage
6         6372   46.107972
3         6372    8.898305
11        6372    8.694288
0         6372    7.862524
14        6372    6.952291
4         6372    5.994978
12        6372    4.912116
10        6372    3.311362
5         6372    1.585060
7         6372    1.239799
2         6372    1.161331
8         6372    1.035782
9         6372    0.188324
1         6372    0.015694
13        6372    0.000000
15        6372    0.000000
16        6372    0.000000

Mapping Statistics:
SKUs with at least one location: 6175
SKUs with no locations: 197
SKUs with multiple locations: 67
Average locations per SKU: 0.98

In [23]:
# Generate key findings report
print("=== KEY FINDINGS AND RECOMMENDATIONS ===")
print("\n" + "="*50)

print("\n1. DATA AVAILABILITY:")
if 'dept_rollup' in locals():
    print("   ✓ Department Rollup data loaded successfully")
    print(f"   - Shape: {dept_rollup.shape}")
    print(f"   - Missing values: {dept_rollup.isnull().sum().sum()}")
else:
    print("   ✗ Department Rollup data not available")

if 'full_data' in locals():
    print("   ✓ Full Data (demand) loaded successfully")
    print(f"   - Shape: {full_data.shape}")
    print(f"   - Missing values: {full_data.isnull().sum().sum()}")
else:
    print("   ✗ Full Data not available")

if 'safety_stock' in locals():
    print("   ✓ Safety Stock data loaded successfully")
    print(f"   - Shape: {safety_stock.shape}")
    print(f"   - Missing values: {safety_stock.isnull().sum().sum()}")
else:
    print("   ✗ Safety Stock data not available")

print("\n2. DATA QUALITY ISSUES:")
print("   - Check for missing lead time variability data")
print("   - Verify data completeness for simulation requirements")
print("   - Validate date formats and ranges")

print("\n3. NEXT STEPS:")
print("   - Map SKUs between datasets")
print("   - Extract lead times and demand patterns")
print("   - Validate data against model requirements")
print("   - Prepare data for simulation implementation")

print("\n4. SIMULATION READINESS:")
required_components = [
    "Lead times for each SKU",
    "SKU-inventory mapping",
    "Historical demand data",
    "Target inventory levels",
    "Service level targets"
]

for component in required_components:
    print(f"   - {component}: [To be verified]")

=== KEY FINDINGS AND RECOMMENDATIONS ===

==================================================

1. DATA AVAILABILITY:
   ✓ Department Rollup data loaded successfully
   - Shape: (6372, 28)
   - Missing values: 108689
   ✓ Full Data (demand) loaded successfully
   - Shape: (86411, 16)
   - Missing values: 827
   ✓ Safety Stock data loaded successfully
   - Shape: (229, 27)
   - Missing values: 3966

2. DATA QUALITY ISSUES:
   - Check for missing lead time variability data
   - Verify data completeness for simulation requirements
   - Validate date formats and ranges

3. NEXT STEPS:
   - Map SKUs between datasets
   - Extract lead times and demand patterns
   - Validate data against model requirements
   - Prepare data for simulation implementation

4. SIMULATION READINESS:
   - Lead times for each SKU: [To be verified]
   - SKU-inventory mapping: [To be verified]
   - Historical demand data: [To be verified]
   - Target inventory levels: [To be verified]
   - Service level targets: [To be verified]

## Summary

This notebook provides a comprehensive review of the Excel data files for the CedarSim inventory management model. The analysis covers:

1. **Data Structure**: Understanding the organization and content of each dataset
2. **Data Quality**: Identifying missing values, outliers, and potential issues
3. **Data Relationships**: Mapping connections between different datasets
4. **Simulation Readiness**: Assessing whether the data meets model requirements

The findings from this analysis will guide the next steps in model development and implementation.